services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
  
  rabbit:
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  app:
    build: app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - rabbit
  
  http_worker:
    build: http_worker
    restart: always
    depends_on:
      - redis
      - rabbit

  worker:
    build: worker
    restart: always
    depends_on:
      - redis
      - rabbit